image: python:3.6

stages:
- test
- deploy

tests:
  stage: test
  coverage: '/TOTAL +\d+ +\d+ +(\d+)%/'
  script:
  - pip3 install tox
  - tox

docs:
  stage: test
  script:
  - pip3 install sphinx
  - make docs
  - mv docs/_build/html/ public
  artifacts:
    paths:
    - public/

deploy-pypi:
  stage: deploy
  script:
  - pip3 install twine
  - make release
  only:
  - tags
