image: python:3.6

stages:
- test
- deploy

tests-py36:
  stage: test
  coverage: '/TOTAL +\d+ +\d+ +(\d+)%/'
  script:
  - pip3 install tox
  - tox -e py36,tests, flake8, behave

tests-py35:
  stage: test
  image: python:3.5
  script:
  - pip3 install tox
  - tox -e py35,tests,flake8,behave

tests-py37:
  stage: test
  image: python:3.7
  script:
  - pip3 install tox
  - tox -e py37,tests,flake8,behave

docs:
  stage: test
  script:
  - pip3 install sphinx
  - make docs
  - mv docs/_build/html/ public
  artifacts:
    paths:
    - public/

deploy-pypi:
  stage: deploy
  script:
  - pip3 install twine
  - make release
  only:
  - tags
