image: python:3.6

stages:
- test
- deploy

tests:
  stage: test
  script:
  - pip3 install tox
  - make test
  - make lint

docs:
  stage: test
  coverage: '/TOTAL +\d+ +\d+ +(\d+\.\d+)%/'
  script:
  - pip3 install sphinx
  - make docs
  - mv docs/_build/html/ public
  artifacts:
    paths:
    - public/

mock-deploy-pypi:
  stage: test
  variables:
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
  script:
  - pip3 install twine
  - make release
  only:
    refs:
    - master

deploy-pypi:
  stage: deploy
  script:
  - pip3 install twine
  - make release
  only:
  - tags
