image: python:3.6

tests:
  stage: test
  script:
  - pip3 install tox
  - make test
  - make lint

docs:
  stage: test
  script:
  - pip3 install sphinx
  - make docs
  - mv docs/_build/html/ public
  artifacts:
    paths:
    - public/
